### ISSUE TITLE
hook failed: "traefik-route-relation-changed" for grafana:ingress

### ISSUE THREAD

**Issue by barrettj12** [canonical/traefik-k8s-operator#112]
### Bug Description

When I try to connect `traefik-k8s` to `grafana-k8s`, the `traefik-route-relation-changed` hook fails.

### To Reproduce

juju deploy grafana-k8s
juju deploy traefik-k8s
juju relate grafana-k8s traefik-k8s

### Environment

Juju 3.0 installed from source
```
$ juju version --all
+ juju version --all
version: 3.0.3-ubuntu-amd64
git-commit: 10fda27abdb2682beef8e47f87de77251cb16864
git-tree-state: clean
compiler: gc
```

MicroK8s installed from snap
```
$ microk8s version
+ microk8s version
MicroK8s v1.25.4 revision 4221
```

`grafana-k8s` rev 52 (`latest/stable`)
`traefik-k8s` rev 93 (`latest/stable`)

### Relevant log output

```shell
unit-traefik-k8s-0: 10:30:33 ERROR unit.traefik-k8s/0.juju-log traefik-route:23: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 710, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/lib/charms/traefik_route_k8s/v0/traefik_route.py", line 166, in _on_relation_changed
    self._update_requirers_with_external_host()
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/lib/charms/traefik_route_k8s/v0/traefik_route.py", line 175, in _update_requirers_with_external_host
    relation.data[self.charm.app]["external_host"] = self._stored.external_host
  File "/var/lib/juju/agents/unit-traefik-k8s-0/charm/venv/ops/model.py", line 945, in __setitem__
    raise RelationDataError('relation data values must be strings')
ops.model.RelationDataError: relation data values must be strings
unit-traefik-k8s-0: 10:30:34 ERROR juju.worker.uniter.operation hook "traefik-route-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by beliaev-maksim** [comment]
@simskij 
I see the same when deploy cos-lite stable on juju 3.0

**Comment by lucabello** [comment]
This doesn't seem to happen anymore on edge; we will promote that to stable soon enough, and then I'll close this issue :)
