### ISSUE TITLE
No app in relationship on relation broken event

### ISSUE THREAD

**Issue by gboutry** [canonical/traefik-k8s-operator#166]
The case that should not happen, did in fact happen:
https://github.com/canonical/traefik-k8s-operator/blob/778af9ab08808ef98a200a88ef07e19dd6fa3585/src/charm.py#L875

After deleting an application, got relation-boken event that failed to resolve because of this assertion
```bash
│ 2023-04-21T07:29:46.227Z [container-agent] 2023-04-21 07:29:46 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-broken" hook                                                                                          │
│ 2023-04-21T07:31:32.103Z [container-agent] 2023-04-21 07:31:32 INFO juju.worker.uniter resolver.go:161 awaiting error resolution for "relation-broken" hook                                                                                          │
│ 2023-04-21T07:31:32.616Z [container-agent] 2023-04-21 07:31:32 INFO juju-log ingress:39: Kubernetes service 'traefik' patched successfully                                                                                                           │
│ 2023-04-21T07:31:32.646Z [container-agent] 2023-04-21 07:31:32 ERROR juju-log ingress:39: Uncaught exception while in charm code:                                                                                                                    │
│ 2023-04-21T07:31:32.646Z [container-agent] Traceback (most recent call last):                                                                                                                                                                        │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "./src/charm.py", line 1000, in <module>                                                                                                                                                           │
│ 2023-04-21T07:31:32.646Z [container-agent]     main(TraefikIngressCharm, use_juju_for_storage=True)                                                                                                                                                  │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 435, in main                                                                                                                    │
│ 2023-04-21T07:31:32.646Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)                                                                                                                                                       │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 144, in _emit_charm_event                                                                                                       │
│ 2023-04-21T07:31:32.646Z [container-agent]     event_to_emit.emit(*args, **kwargs)                                                                                                                                                                   │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 355, in emit                                                                                                               │
│ 2023-04-21T07:31:32.646Z [container-agent]     framework._emit(event)  # noqa                                                                                                                                                                        │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 824, in _emit                                                                                                              │
│ 2023-04-21T07:31:32.646Z [container-agent]     self._reemit(event_path)                                                                                                                                                                              │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 899, in _reemit                                                                                                            │
│ 2023-04-21T07:31:32.646Z [container-agent]     custom_handler(event)                                                                                                                                                                                 │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/traefik_k8s/v1/ingress.py", line 280, in _handle_relation_broken                                                                             │
│ 2023-04-21T07:31:32.646Z [container-agent]     self.on.data_removed.emit(event.relation)  # type: ignore                                                                                                                                             │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 355, in emit                                                                                                               │
│ 2023-04-21T07:31:32.646Z [container-agent]     framework._emit(event)  # noqa                                                                                                                                                                        │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 824, in _emit                                                                                                              │
│ 2023-04-21T07:31:32.646Z [container-agent]     self._reemit(event_path)                                                                                                                                                                              │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 899, in _reemit                                                                                                            │
│ 2023-04-21T07:31:32.646Z [container-agent]     custom_handler(event)                                                                                                                                                                                 │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "./src/charm.py", line 556, in _handle_ingress_data_removed                                                                                                                                        │
│ 2023-04-21T07:31:32.646Z [container-agent]     self._wipe_ingress_for_relation(                                                                                                                                                                      │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "./src/charm.py", line 833, in _wipe_ingress_for_relation                                                                                                                                          │
│ 2023-04-21T07:31:32.646Z [container-agent]     config_path = f"{_DYNAMIC_CONFIG_DIR}/{self._relation_config_file(relation)}"                                                                                                                         │
│ 2023-04-21T07:31:32.646Z [container-agent]   File "./src/charm.py", line 852, in _relation_config_file                                                                                                                                               │
│ 2023-04-21T07:31:32.646Z [container-agent]     assert relation.app, "no app in relation (shouldn't happen)"  # for type checker                                                                                                                      │
│ 2023-04-21T07:31:32.646Z [container-agent] AssertionError: no app in relation (shouldn't happen)
```

Looking at what's done next, it doesn't look like this would have been resolved either way.

**Comment by PietroPasotti** [comment]
What revision of the charm are you using? The line numbers don't match with what's on `main` and the line of code that's raising is behind a guard that should catch this situation:
![image](https://user-images.githubusercontent.com/6230162/233618023-d811ac12-f367-4c97-b93d-b5ad9711eb66.png)

**Comment by gboutry** [comment]
Revision 110 from `1.0/stable`

**Comment by PietroPasotti** [comment]
The release pipeline has been stuck by failing itests for a week, that might explain the discrepancy. @simskij what do we do?

**Comment by simskij** [comment]
Once https://github.com/canonical/traefik-k8s-operator/pull/165 is solved and merged, this will likely go away.

**Comment by simskij** [comment]
This still happens on rev 126 from `latest/edge`.

```

Traceback (most recent call last):
  File "./src/charm.py", line 540, in <module>
    main(LokiOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/traefik_k8s/v1/ingress_per_unit.py", line 741, in _handle_relation
    self._publish_auto_data()
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/traefik_k8s/v1/ingress_per_unit.py", line 749, in _publish_auto_data
    self.provide_ingress_requirements(host=self._host, port=self._port)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/traefik_k8s/v1/ingress_per_unit.py", line 793, in provide_ingress_requirements
    self.relation.data[self.unit].update(data)
  File "/usr/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1475, in __setitem__
    self._commit(key, value)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1479, in _commit
    self._backend.update_relation_data(self.relation.id, self._entity, key, value)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2947, in update_relation_data
    self.relation_set(relation_id, key, value, isinstance(_entity, Application))
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2721, in relation_set
    self._run(*args, input_stream=content)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 2618, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: ERROR cannot read relation settings: unit "loki/0": settings not found
```

**Comment by simskij** [comment]
Integration tests have been working for quite a while now. If this is still an problem, please go ahead and open a new issue.
