### ISSUE TITLE
Exception when remote IPA app departs

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#211]
### Bug Description

When a remote IPA app is departed, we get a traceback and traefik goes into error state because "no app in realtion".

https://github.com/canonical/traefik-k8s-operator/blob/093c8779acd2d1206a8542fa423b3acf0bacd042/lib/charms/traefik_k8s/v2/ingress.py#L378-L379

### To Reproduce

1. Relate traefik and alertmanager.
2. Remove alertmanager.

### Environment

```
Model   Controller  Cloud/Region        Version  SLA          Timestamp
amanda  microk8s    microk8s/localhost  3.2.0    unsupported  22:14:06-04:00

App   Version  Status      Scale  Charm             Channel  Rev  Address         Exposed  Message
am    0.25.0   terminated    0/1  alertmanager-k8s  edge      81  10.152.183.200  no       unit stopped by the cloud
av             active          1  avalanche-k8s     edge      35  10.152.183.81   no       
prom  2.33.5   active          1  prometheus-k8s    stable   103  10.152.183.184  no       
trfk  2.9.6    waiting         1  traefik-k8s       stable   110  10.43.8.219     no       waiting for units to settle down

Unit     Workload    Agent  Address       Ports  Message
am/0     terminated  lost   10.1.166.80          unit stopped by the cloud
av/0*    active      idle   10.1.166.106         
prom/0*  active      idle   10.1.166.116         
trfk/0*  error       idle   10.1.166.82          hook failed: "ingress-relation-broken" for am:ingress

Relation provider      Requirer               Interface          Type     Message
av:metrics-endpoint    prom:metrics-endpoint  prometheus_scrape  regular  
av:replicas            av:replicas            avalanche_replica  peer     
prom:prometheus-peers  prom:prometheus-peers  prometheus_peers   peer     
trfk:ingress           am:ingress             ingress            regular  
```

### Relevant log output

```shell
unit-trfk-0: 21:59:47.033 DEBUG unit.trfk/0.juju-log ingress:46: Wiping the ingress setup for the 'ingress:46' relation
unit-trfk-0: 21:59:47.036 ERROR unit.trfk/0.juju-log ingress:46: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1000, in <module>
    main(TraefikIngressCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/main.py", line 435, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-trfk-0/charm/lib/charms/traefik_k8s/v1/ingress.py", line 280, in _handle_relation_broken
    self.on.data_removed.emit(event.relation)  # type: ignore
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-trfk-0/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 556, in _handle_ingress_data_removed
    self._wipe_ingress_for_relation(
  File "./src/charm.py", line 833, in _wipe_ingress_for_relation
    config_path = f"{_DYNAMIC_CONFIG_DIR}/{self._relation_config_file(relation)}"
  File "./src/charm.py", line 852, in _relation_config_file
    assert relation.app, "no app in relation (shouldn't happen)"  # for type checker
AssertionError: no app in relation (shouldn't happen)
```

**Comment by Abuelodelanada** [comment]
1. I have deployed traefik and alermanager:

```shell
$ jst                                                                                                                                127 ↵
Model  Controller  Cloud/Region        Version  SLA          Timestamp
test   microk8s    microk8s/localhost  3.5.1    unsupported  10:16:49-03:00

App      Version  Status  Scale  Charm             Channel      Rev  Address         Exposed  Message
am       0.27.0   active      1  alertmanager-k8s  latest/edge  124  10.152.183.212  no       
traefik  2.11.0   active      1  traefik-k8s       latest/edge  199  10.152.183.93   no       Serving at 192.168.1.253

Unit        Workload  Agent  Address     Ports  Message
am/0*       active    idle   10.1.9.231         
traefik/0*  active    idle   10.1.9.230         Serving at 192.168.1.253

Integration provider  Requirer       Interface             Type     Message
am:replicas           am:replicas    alertmanager_replica  peer     
traefik:ingress       am:ingress     ingress               regular  
traefik:peers         traefik:peers  traefik_peers         peer 
```

2. I remove alertmanager: `$ juju remove-application am`
3. The model ends up in a good shape:

```shell
$ jst                       
Model  Controller  Cloud/Region        Version  SLA          Timestamp
test   microk8s    microk8s/localhost  3.5.1    unsupported  10:18:47-03:00

App      Version  Status  Scale  Charm        Channel      Rev  Address        Exposed  Message
traefik  2.11.0   active      1  traefik-k8s  latest/edge  199  10.152.183.93  no       Serving at 192.168.1.253

Unit        Workload  Agent  Address     Ports  Message
traefik/0*  active    idle   10.1.9.230         Serving at 192.168.1.253

Integration provider  Requirer       Interface      Type  Message
traefik:peers         traefik:peers  traefik_peers  peer  
```
4. There are no ERROR messages in juju debug-log


Closing because it is not reproducible with the current version of the charms.
