### ISSUE TITLE
"ERROR permission denied" when removing relation between Traefik and consumer charm 

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/traefik-k8s-operator#34]
### Bug Description

When a relation between Traefik operator and a consumer charm (let's say Loki) that use `IngressPerUnitRequirer`, an `ops.model.ModelError` exception is raised

### To Reproduce

1. Deploy this charm
2. Deploy a consumer charm that uses `IngressPerUnitRequirer` (let's say Loki)
3. Run `juju add-relation traefik-ingress loki` 
4. Run `juju remove-relation traefik-ingress loki`
5. Check logs with `juju debug-log`

### Environment

Both charms are packed from source code, running in `charm-dev` Multipass workflow.

### Relevant log output

```shell
unit-loki-0: 16:18:56 ERROR unit.loki/0.juju-log logging:16: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1595, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-loki-0/network-get', 'ingress-per-unit', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 290, in <module>
    main(LokiOperatorCharm)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 419, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 59, in __init__
    self.ingress_per_unit = IngressPerUnitRequirer(
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/traefik_k8s/v0/ingress_per_unit.py", line 353, in __init__
    self.auto_data = self._complete_request(host or "", port)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/traefik_k8s/v0/ingress_per_unit.py", line 376, in _complete_request
    host = str(binding.network.bind_address)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 556, in network
    self._network = Network(self._backend.network_get(self.name, self._relation_id))
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1851, in network_get
    return self._run(*cmd, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1597, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR unit "loki/0" not found (not found)\n'
```

### Additional context

Seems the problem is in `_complete_request` method when executing [`host = str(binding.network.bind_address)`](https://github.com/canonical/traefik-k8s-operator/blob/main/lib/charms/traefik_k8s/v0/ingress_per_unit.py#L376):

```python
    def _complete_request(self, host: Optional[str], port: int):
        if not host:
            binding = self.charm.model.get_binding(self.endpoint)
            host = str(binding.network.bind_address)

        return {
            self.charm.unit: {
                "model": self.model.name,
                "name": self.charm.unit.name,
                "host": host,
                "port": port,
            },
        }
```

**Comment by Abuelodelanada** [comment]
Some minutes after this error, when a `update-status` event is fired, the following error happens:

```
unit-traefik-ingress-0: 16:23:58 ERROR unit.traefik-ingress/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/model.py", line 1595, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-traefik-ingress-0/relation-get', '-r', '18', '-', 'loki', '--app', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 501, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 283, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 743, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/framework.py", line 790, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 177, in _on_update_status
    self._process_status_and_configurations()
  File "./src/charm.py", line 222, in _process_status_and_configurations
    self._process_ingress_relation(ingress_relation)
  File "./src/charm.py", line 250, in _process_ingress_relation
    if not (provider := self._provider_from_relation(relation)).is_ready(relation):
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/serialized_data_interface/relation.py", line 216, in is_ready
    data = self.unwrap(relation)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/serialized_data_interface/relation.py", line 290, in unwrap
    return self._sdi.unwrap(relation)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/serialized_data_interface/sdi.py", line 262, in unwrap
    version = self.get_version(relation)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/serialized_data_interface/sdi.py", line 108, in get_version
    remote_versions_raw = relation.data[relation.app].get(utils.VERSION_KEY)
  File "/usr/lib/python3.8/_collections_abc.py", line 660, in get
    return self[key]
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/model.py", line 433, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/model.py", line 417, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/model.py", line 782, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/model.py", line 1662, in relation_get
    return self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-traefik-ingress-0/charm/venv/ops/model.py", line 1597, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR permission denied\n'
```

**Comment by sed-i** [comment]
Similar to https://github.com/canonical/loki-k8s-operator/issues/102

**Comment by mmanciop** [comment]
It's because of https://github.com/canonical/operator/issues/693 :-(

**Comment by sed-i** [comment]
I see a very similar error between loki and loki-tester on relation-departed that is fired due to app removal:
For some reason relation-get fails for `ops.model.ModelError: b'ERROR permission denied\n'`

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-loki-k8s-1/charm/venv/ops/model.py", line 1595, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-loki-k8s-1/relation-get', '-r', '4', '-', 'loki-tester', '--app', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

# ...

  File "/var/lib/juju/agents/unit-loki-k8s-1/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1266, in _process_logging_relation_changed
    if relation.data.get(relation.app).get("alert_rules"):
  File "/usr/lib/python3.8/_collections_abc.py", line 660, in get
    return self[key]
  File "/var/lib/juju/agents/unit-loki-k8s-1/charm/venv/ops/model.py", line 433, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-loki-k8s-1/charm/venv/ops/model.py", line 417, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-loki-k8s-1/charm/venv/ops/model.py", line 782, in _load
    return self._backend.relation_get(self.relation.id, self._entity.name, self._is_app)
  File "/var/lib/juju/agents/unit-loki-k8s-1/charm/venv/ops/model.py", line 1662, in relation_get
    return self._run(*args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-loki-k8s-1/charm/venv/ops/model.py", line 1597, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR permission denied\n'
```

**Comment by mmanciop** [comment]
Indeed it's because the `RELATION_NAME` is not set over a `relation_broken` hook, and that trips https://github.com/canonical/operator/issues/693
