### ISSUE TITLE
issue with TLS and tracing 

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/traefik-k8s-operator#389]
### Bug Description

traefik emits error logs when related to tempo over tracing with tls enabled

### To Reproduce

juju deploy cos-lite --channel edge --trust
juju deploy tls-overlay
juju deploy tempo-k8s --channel edge --trust tempo
jhack imatrix fill

### Environment

juju 3.5

### Relevant log output

```shell
unit-traefik-0: 11:47:01 ERROR unit.traefik/0.juju-log logging:34: Exception while exporting Span batch.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/opentelemetry/sdk/trace/export/__init__.py", line 368, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 145, in expo
rt
    resp = self._export(serialized_data)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 114, in _exp
ort
    return self._session.post(
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/requests/adapters.py", line 639, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/requests/adapters.py", line 328, in cert_verify
    raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/traefik/juju/server.cert
```

**Comment by PietroPasotti** [comment]
maybe something went wrong with the relation to self-signed certs: pebble logs are full of:
```
ificates configured"                                                                                                                           
2024-08-01T09:51:31.603Z [traefik] time="2024-08-01T09:51:31Z" level=debug msg="Serving default certificate for request: \"\""                 
2024-08-01T09:51:31.603Z [traefik] time="2024-08-01T09:51:31Z" level=debug msg="http: TLS handshake error from 192.168.2.23:39118: tls: no cert
ificates configured"                                                                                                                           
```

**Comment by PietroPasotti** [comment]
todo: reproduce with edge

**Comment by mmkay** [comment]
After repro attempts with edge it looks like this is not happening anymore.
