### ISSUE TITLE
Cannot index relation data with "None"

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/traefik-k8s-operator#99]
### Bug Description

When removing a relation (`traefik_route` interface) between traefik-k8s and grafana-k8s, and `KeyError` exception is raised:

```
KeyError: 'Cannot index relation data with "None". Are you trying to access remote app data during a relation-broken event? This is not allowed.'
```

### To Reproduce

1. Deploy cos: `juju deploy cos-lite --trust`
2. Wait until all units are in `active` status
3. Remove relations, for instance: `jhack imatrix clear`
4. See in `juju debug-log` the errors

### Environment

juju: 3.0.0 (and 2.9.35 as well)
microk8s: 1.25-strict

### Relevant log output

```shell
unit-grafana-0: 00:56:30.249 INFO juju.worker.uniter.operation ran "grafana-source-relation-broken" hook (via hook dispatching script: dispatch)
unit-grafana-0: 00:56:32.056 ERROR unit.grafana/0.juju-log ingress:5: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1156, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 426, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 210, in __init__
    url=self.external_url,
  File "./src/charm.py", line 1068, in external_url
    if self.ingress.external_host:
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/traefik_route_k8s/v0/traefik_route.py", line 220, in external_host
    self._update_stored_external_host()
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/traefik_route_k8s/v0/traefik_route.py", line 235, in _update_stored_external_host
    external_host = relation.data[relation.app].get("external_host", "")
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/model.py", line 914, in __getitem__
    raise KeyError(
KeyError: 'Cannot index relation data with "None". Are you trying to access remote app data during a relation-broken event? This is not allowed.'
unit-grafana-0: 00:56:32.564 ERROR juju.worker.uniter.operation hook "ingress-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by PietroPasotti** [comment]
should be fixed by https://github.com/canonical/traefik-route-k8s-operator/pull/17
